import Head from 'next/head';
import { NextPageWithLayout } from './_app';
import { ReactElement } from 'react';
import Layout from '../components/layout';
import Post from '../components/post';
import ErrorModal from '../components/error-modal';

const Home: NextPageWithLayout = () => {
  const closeModal = () => {
  };

  return (
    <>
      <Head>
        <title>みやイベ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen items-center py-12 sm:py-0 px-4 sm:px-64 justify-center sm:justify-between flex-wrap gap-12 sm:gap-0">
        {new Array(4).fill(null).map((_, index) => {
          return (
            <Post thumbnail="dummyString" title="dummyString" userImage="dummyString" key={index}/>
          );
        })}
      </div>
      <ErrorModal isOpen closeModal={closeModal}/>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  );
}

export default Home;