import Head from 'next/head';
import { NextPageWithLayout } from './_app';
import { ReactElement } from 'react';
import Layout from '../components/layout';
import {  GetServerSideProps, InferGetServerSidePropsType } from 'next';
import { Post } from '../types/post';
import  PostComp from '../components/post';
import { adminDB } from '../firebase/server-app';
import { useUser } from '../context/user-context';
import Link from 'next/link';

export const getServerSideProps: GetServerSideProps<{ posts: Post[] | undefined }> = async () => {
  let posts = undefined;

  try {
    const snap = await adminDB.collection("posts").orderBy("createdAt", "desc").get();
    posts = snap.docs.map(doc => doc.data() as Post);
  }
  catch (err) {
    console.log("記事群取得エラー :", err);
  }

  return {
    props: {
      posts
    },
  }
}


const Home: NextPageWithLayout<InferGetServerSidePropsType<typeof getServerSideProps>> = ({posts}) => {
  const { currentUser } = useUser()

  return (
    <>
      <Head>
        <title>みやイベ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="flex min-h-screen py-12 sm:py-0 px-4 sm:px-60 justify-center sm:justify-between flex-wrap gap-12 sm:gap-0 overflow-y-scroll ">
        {!currentUser &&
        <div className="flex w-full bg-white h-8 sm:h-10 items-center justify-center">
          <Link href="/about" className="p-2align-middle tracking-wider text-black text-xs sm:text-sm" ><span className="font-semibold text-orange-500 text-sm sm:text-base">みや</span><span className="font-semibold text-green-600  text-sm sm:text-base">イベ</span>について</Link>
        </div>
        }
        {posts?.map((post: Post) => {
          return (
            <PostComp postId={post.id} thumbnail={post.thumbnailURL} title={post.title} authorId={post.authorId} key={post.id}/>
          );
        })}
      </div>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  );
}

export default Home;